# Generated by Django 5.2.4 on 2025-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('GROUP_HEAD', 'Group Head'), ('MASTER', 'Master'), ('SMU', 'SMU')], db_column='role', default='USER', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
